server:
  port: 8091

springfox:
  title: 'FINT SSE Adapter Skeleton'
  version: '@version@'

fint:
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
    organizations: fintlabs.no

  p360:
    documentargs:
      sakmappetype-mapping:
        - sakmappetype: 27
          documentarchive: 150003

  oauth:
    enabled: true
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client
    username: ${fint.core.oauth2.username}
    password: ${fint.core.oauth2.password}
    client-id: ${fint.core.oauth2.client-id}
    client-secret: ${fint.core.oauth2.client-secret}

security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
