apiVersion: fintlabs.no/v1alpha1
kind: FintAdapter
metadata:
  name: arkiv-p360-beta
  namespace: telemarkfylke-no
  labels:
    app.kubernetes.io/name: adapter-arkiv-p360
    app.kubernetes.io/instance: adapter-arkiv-p360_telemarkfylke-no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter-arkiv-p360
    app.kubernetes.io/part-of: arkiv
    fintlabs.no/team: arkiv
    fintlabs.no/org-id: telemarkfylke.no

spec:
  orgId: telemarkfylke.no
  note: Brukes av p360-arkiv-adapter. Automatisk opprettet ved oppretting av adapter.
  components:
    - arkiv_kodeverk
    - arkiv_noark
    - arkiv_kulturminnevern
    - arkiv_samferdsel
