apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vestfoldfylke-no

resources:
  - ../../../base
  - onepassword.yaml
  - fint-adapter.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-p360-arkiv_vestfoldfylke-no
  fintlabs.no/org-id: vestfoldfylke.no

patches:

  - target:
      kind: Deployment
      name: adapter-p360-arkiv
    path: deployment.yaml
