apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agderfk-no

resources:
  - ../../../base
  - onepassword.yaml

commonLabels:
  app.kubernetes.io/instance: adapter-arkiv-p360_agderfk-no
  fintlabs.no/org-id: agderfk.no

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-p360
    path: deployment.yaml
