apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tromsfylke-no

resources:
  - ../../../base
  - onepassword.yaml
  - fint-adapter.yaml

labels:
  - pairs:
      fintlabs.no/org-id: tromsfylke.no
      app.kubernetes.io/instance: adapter-arkiv-p360_tromsfylke-no
    includeSelectors: true

patches:
  
  - target:
      kind: Deployment
      name: adapter-arkiv-p360
    path: deployment.yaml
