apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-arkiv-p360
  labels:
    app.kubernetes.io/instance: adapter-arkiv-p360_fintlabs_no
    app.kubernetes.io/name: adapter-arkiv-p360
    fintlabs.no/team: arkiv
    fintlabs.no/org-id: fintlabs.no
    observability.fintlabs.no/loki: true
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: adapter-arkiv-p360
  template:
    metadata:
      labels:
        app: adapter-arkiv-p360
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8091"
          prometheus.io/path: "actuator/prometheus"
    spec:
      restartPolicy: Always
      volumes:
        - name: tempdir
          emptyDir:
            sizeLimit: 1G
      containers:
        - name: adapter-arkiv-p360
          image: ghcr.io/fintlabs/fint-p360-rpc-arkiv-adapter:empty
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 8091
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: tempdir
              mountPath: /temp
          env:
            - {name: TZ, value: Europe/Oslo}
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xmx1G -verbose:gc
                -XX:+ExitOnOutOfMemoryError
                -Dfile.encoding=UTF-8
            - {name: security.basic.enabled, value: "false"}
            - {name: fint.adapter.reject-unknown-events, value: 'true'}
            - {name: fint.case.coding.filformat.RA-JPEG, value: 'JPG'}
            - {name: fint.case.coding.filformat.RA-PDF, value: 'PDF'}
            - {name: fint.case.coding.filformat.RA-TEKST, value: 'TXT'}
            - {name: fint.case.coding.filformat.RA-TIFF6, value: 'TIF'}
            - {name: fint.file-cache.directory, value: '/temp'}
